[package]
name = "vendor-controller"
version = "1.1.1"
edition = "2024"

[dependencies]
gtin = { git = "https://github.com/areif-dev/gtin", version = "1.0.0" }
fantoccini = "0.22.0"
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
